#debug: true

server:
  forward-headers-strategy: native


spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - PreserveHostHeader
        - TokenRelay
        - Abac

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'