#debug: true

server:
  forward-headers-strategy: native

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: INFO

spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - PreserveHostHeader
        - TokenRelay
        - Abac

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'